#!/usr/bin/env bash
# =============================================================================
#  install-cups-printer.sh — register Cipherjet as a real printer (CUPS).
#
#  After this runs, "Cipherjet (Encrypted)" appears in System Settings ▸
#  Printers and in every app's Print dialog (macOS & Linux). Printing to it
#  encrypts the job into a root-owned system spool; decryption/release is an
#  admin-only operation (see cipherjet-admin, installed below).
#
#  It ensures the binaries are SELF-CONTAINED (static libsodium). This matters on
#  macOS: the CUPS sandbox blocks a backend from loading a Homebrew dylib out of
#  /usr/local, which is a common cause of "Something went wrong when printing".
#
#  Run with sudo:   sudo ./install/install-cups-printer.sh
#
#  Installs to /usr/local/bin (already on PATH): cipherjet, cipherjet-release,
#  cipherjet-keygen, cipherjet-send, cipherjet-server, cipherjet-admin,
#  cipherjet-print; plus the CUPS backend, a "Cipherjet" queue, and the system
#  key/spool under /usr/local/{etc,var}/cipherjet.
# =============================================================================
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "Please run with sudo:  sudo $0" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="${CIPHERJET_BUILD:-$PROJECT_DIR/build}"
SODIUM_PREFIX="$PROJECT_DIR/.sodium-static"
SODIUM_VER="1.0.20"

QUEUE_NAME="${CIPHERJET_QUEUE:-Cipherjet}"
BIN_DIR="/usr/local/bin"
ETC_DIR="/usr/local/etc/cipherjet"
VAR_DIR="/usr/local/var/cipherjet"
PASS_FILE="$ETC_DIR/passphrase"

OS="$(uname -s)"
if   [ -d /usr/libexec/cups/backend ]; then BACKEND_DIR=/usr/libexec/cups/backend   # macOS
elif [ -d /usr/lib/cups/backend ];     then BACKEND_DIR=/usr/lib/cups/backend       # Linux
else echo "Cannot find the CUPS backend directory." >&2; exit 1; fi

# --- Is the current cipherjet binary self-contained (no external libsodium)? --
binary_is_static() {
  [ -x "$BUILD_DIR/cipherjet" ] || return 1
  if [ "$OS" = "Darwin" ]; then
    ! otool -L "$BUILD_DIR/cipherjet" 2>/dev/null | grep -qi sodium
  else
    ! ldd "$BUILD_DIR/cipherjet" 2>/dev/null | grep -qi sodium
  fi
}

ensure_static_build() {
  if binary_is_static; then
    echo "==> Using existing self-contained build in $BUILD_DIR"
    return
  fi
  echo "==> Building self-contained binaries (static libsodium) so the CUPS"
  echo "    backend has no external library the sandbox can block."
  if [ ! -f "$SODIUM_PREFIX/lib/libsodium.a" ]; then
    echo "    - building static libsodium $SODIUM_VER"
    tmp="$(mktemp -d)"
    curl -fsSL -o "$tmp/libsodium.tar.gz" \
      "https://download.libsodium.org/libsodium/releases/libsodium-${SODIUM_VER}-stable.tar.gz"
    tar xzf "$tmp/libsodium.tar.gz" -C "$tmp"
    ( cd "$tmp/libsodium-stable" \
      && ./configure --enable-static --disable-shared --prefix="$SODIUM_PREFIX" >/dev/null \
      && make -j >/dev/null && make install >/dev/null )
    rm -rf "$tmp"
  fi
  echo "    - building Cipherjet"
  cmake -S "$PROJECT_DIR" -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release \
        -DCIPHERJET_SODIUM_ROOT="$SODIUM_PREFIX" >/dev/null
  cmake --build "$BUILD_DIR" -j >/dev/null
}

ensure_static_build

echo "==> Installing binaries into $BIN_DIR (on your PATH)"
for b in cipherjet cipherjet-release cipherjet-keygen cipherjet-send cipherjet-server; do
  install -m 0755 "$BUILD_DIR/$b" "$BIN_DIR/$b"
done
# The everyday CLI wrapper (finds the installed binaries on PATH).
install -m 0755 "$PROJECT_DIR/bin/cipherjet-print" "$BIN_DIR/cipherjet-print"

echo "==> Preparing system directories (root-owned)"
mkdir -p "$ETC_DIR" "$VAR_DIR"
chmod 700 "$ETC_DIR" "$VAR_DIR"

if [ ! -f "$PASS_FILE" ]; then
  echo "==> Generating master-key passphrase at $PASS_FILE"
  umask 077
  head -c 32 /dev/urandom | base64 | tr -d '\n' > "$PASS_FILE"
  chmod 600 "$PASS_FILE"
fi

echo "==> Creating the master key (if absent)"
CIPHERJET_HOME="$VAR_DIR" CIPHERJET_PASSPHRASE_FILE="$PASS_FILE" \
  "$BIN_DIR/cipherjet-keygen" init --strength moderate 2>/dev/null \
  && echo "    master key created." \
  || echo "    master key already present."

echo "==> Installing CUPS backend wrapper into $BACKEND_DIR/cipherjet"
cat > "$BACKEND_DIR/cipherjet" <<EOF
#!/bin/sh
# Cipherjet CUPS backend — auto-generated by install-cups-printer.sh
if [ "\$#" -eq 0 ]; then exec "$BIN_DIR/cipherjet"; fi
export CIPHERJET_HOME="$VAR_DIR"
export CIPHERJET_PASSPHRASE_FILE="$PASS_FILE"
exec "$BIN_DIR/cipherjet" "\$@"
EOF
chown root "$BACKEND_DIR/cipherjet" 2>/dev/null || true
chmod 0700 "$BACKEND_DIR/cipherjet"

echo "==> Installing admin helper $BIN_DIR/cipherjet-admin"
cat > "$BIN_DIR/cipherjet-admin" <<EOF
#!/bin/sh
# Release/list/audit the system spool. Use with sudo:
#   sudo cipherjet-admin list
#   sudo cipherjet-admin release <job-id> | lp -d <printer>
export CIPHERJET_HOME="$VAR_DIR"
export CIPHERJET_PASSPHRASE_FILE="$PASS_FILE"
exec "$BIN_DIR/cipherjet-release" "\$@"
EOF
chmod 0755 "$BIN_DIR/cipherjet-admin"

echo "==> Creating the CUPS print queue '$QUEUE_NAME'"
# Modern macOS removed "raw" queues, so use a minimal pass-through PPD: it hands
# the job (PDF/PostScript) straight to the cipherjet backend, which encrypts it.
PPD="$SCRIPT_DIR/cipherjet.ppd"
[ -f "$PPD" ] || { echo "missing PPD: $PPD" >&2; exit 1; }
lpadmin -x "$QUEUE_NAME" 2>/dev/null || true   # clear any half-created queue
lpadmin -p "$QUEUE_NAME" -E -v "cipherjet:/secure-spool" -P "$PPD" \
        -D "Cipherjet (Encrypted)" -L "Secure encrypted spool"
cupsenable "$QUEUE_NAME" || true
cupsaccept "$QUEUE_NAME" || true

# --- Self-test: print through the queue and confirm a job was encrypted -------
echo "==> Self-test: sending a job through the queue..."
before=$(CIPHERJET_HOME="$VAR_DIR" CIPHERJET_PASSPHRASE_FILE="$PASS_FILE" \
         "$BIN_DIR/cipherjet-release" list 2>&1 | grep -Ec '^[0-9a-f]{32}' || true)
printf 'Cipherjet install self-test\n' | lp -d "$QUEUE_NAME" >/dev/null 2>&1 || true
sleep 3
after=$(CIPHERJET_HOME="$VAR_DIR" CIPHERJET_PASSPHRASE_FILE="$PASS_FILE" \
        "$BIN_DIR/cipherjet-release" list 2>&1 | grep -Ec '^[0-9a-f]{32}' || true)

echo
if [ "$after" -gt "$before" ]; then
  echo "✔ Self-test PASSED — a job was encrypted into the spool via CUPS."
  echo "  \"Cipherjet (Encrypted)\" now works from any app's Print dialog (⌘P)."
else
  echo "✗ Self-test did NOT see a new job. The CUPS sandbox may still be blocking"
  echo "  the backend. As a fallback, allow unsandboxed backends and retry:"
  echo "      echo 'Sandboxing off' | sudo tee -a /etc/cups/cups-files.conf"
  echo "      sudo launchctl kickstart -k system/org.cups.cupsd   # macOS"
  echo "  Then: printf 'test\\n' | lp -d $QUEUE_NAME ; sudo cipherjet-admin list"
fi

cat <<EOF

Everything is on your PATH now (/usr/local/bin), so from anywhere you can:
    cipherjet-print print file.pdf     # personal encrypt-and-hold, then:
    cipherjet-print release-all        # send to your default printer
    cipherjet-send file.pdf            # print to a Cipherjet server on the LAN
    sudo cipherjet-admin list          # inspect the system print queue's spool
    sudo cipherjet-admin release <id> | lp -d IT_MONITORING_1

Remove everything:  sudo ./install/uninstall-cups-printer.sh
EOF
