#!/usr/bin/env bash
# =============================================================================
#  install-cups-printer.sh — register Cipherjet as a real printer (CUPS).
#
#  After this runs, "Cipherjet (Encrypted)" appears in System Settings ▸
#  Printers and in every app's Print dialog (macOS & Linux). Printing to it
#  encrypts the job into a root-owned system spool; decryption/release is an
#  admin-only operation (see cipherjet-admin, installed below).
#
#  Run with sudo:   sudo ./install/install-cups-printer.sh
#
#  What it installs:
#    /usr/local/bin/cipherjet{,-release,-keygen}   the built binaries
#    /usr/local/bin/cipherjet-admin                 root helper for release/list
#    /usr/local/etc/cipherjet/passphrase            master-key passphrase (0600)
#    /usr/local/var/cipherjet/                       system data dir (key+spool)
#    <cups-backend-dir>/cipherjet                    CUPS backend wrapper
#    a CUPS queue named "Cipherjet"
# =============================================================================
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "Please run with sudo:  sudo $0" >&2
  exit 1
fi

# --- Resolve paths -----------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="${CIPHERJET_BUILD:-$PROJECT_DIR/build}"

QUEUE_NAME="${CIPHERJET_QUEUE:-Cipherjet}"
BIN_DIR="/usr/local/bin"
ETC_DIR="/usr/local/etc/cipherjet"
VAR_DIR="/usr/local/var/cipherjet"
PASS_FILE="$ETC_DIR/passphrase"

# CUPS backend directory differs by OS.
if   [ -d /usr/libexec/cups/backend ]; then BACKEND_DIR=/usr/libexec/cups/backend   # macOS
elif [ -d /usr/lib/cups/backend ];     then BACKEND_DIR=/usr/lib/cups/backend       # Linux
else echo "Cannot find the CUPS backend directory." >&2; exit 1; fi

for b in cipherjet cipherjet-release cipherjet-keygen; do
  [ -x "$BUILD_DIR/$b" ] || { echo "Missing $BUILD_DIR/$b — build the project first:
    cmake -S \"$PROJECT_DIR\" -B \"$BUILD_DIR\" -DCMAKE_BUILD_TYPE=Release && cmake --build \"$BUILD_DIR\" -j" >&2; exit 1; }
done

echo "==> Installing binaries into $BIN_DIR"
install -m 0755 "$BUILD_DIR/cipherjet"         "$BIN_DIR/cipherjet"
install -m 0755 "$BUILD_DIR/cipherjet-release" "$BIN_DIR/cipherjet-release"
install -m 0755 "$BUILD_DIR/cipherjet-keygen"  "$BIN_DIR/cipherjet-keygen"

echo "==> Preparing system directories (root-owned)"
mkdir -p "$ETC_DIR" "$VAR_DIR"
chmod 700 "$ETC_DIR" "$VAR_DIR"

if [ ! -f "$PASS_FILE" ]; then
  echo "==> Generating master-key passphrase at $PASS_FILE"
  umask 077
  head -c 32 /dev/urandom | base64 | tr -d '\n' > "$PASS_FILE"
  chmod 600 "$PASS_FILE"
fi

echo "==> Creating the master key (if absent)"
CIPHERJET_HOME="$VAR_DIR" CIPHERJET_PASSPHRASE_FILE="$PASS_FILE" \
  "$BIN_DIR/cipherjet-keygen" init --strength moderate 2>/dev/null \
  && echo "    master key created." \
  || echo "    master key already present."

echo "==> Installing CUPS backend wrapper into $BACKEND_DIR/cipherjet"
# The wrapper injects the system data dir + passphrase file, then execs the
# real binary. With no arguments (CUPS device discovery) it just advertises.
cat > "$BACKEND_DIR/cipherjet" <<EOF
#!/bin/sh
# Cipherjet CUPS backend — auto-generated by install-cups-printer.sh
if [ "\$#" -eq 0 ]; then exec "$BIN_DIR/cipherjet"; fi
export CIPHERJET_HOME="$VAR_DIR"
export CIPHERJET_PASSPHRASE_FILE="$PASS_FILE"
exec "$BIN_DIR/cipherjet" "\$@"
EOF
# 0700 root-owned => CUPS runs the backend as root, which can read the
# passphrase file and own the spool. Decryption is likewise admin-only.
chown root "$BACKEND_DIR/cipherjet" 2>/dev/null || true
chmod 0700 "$BACKEND_DIR/cipherjet"

echo "==> Installing admin helper $BIN_DIR/cipherjet-admin"
cat > "$BIN_DIR/cipherjet-admin" <<EOF
#!/bin/sh
# Run the release/list/audit tools against the system spool. Use with sudo:
#   sudo cipherjet-admin list
#   sudo cipherjet-admin release <job-id> | lp -d <printer>
export CIPHERJET_HOME="$VAR_DIR"
export CIPHERJET_PASSPHRASE_FILE="$PASS_FILE"
exec "$BIN_DIR/cipherjet-release" "\$@"
EOF
chmod 0755 "$BIN_DIR/cipherjet-admin"

echo "==> Creating the CUPS print queue '$QUEUE_NAME'"
# A raw queue passes the application's print data straight to our backend.
lpadmin -p "$QUEUE_NAME" -E -v "cipherjet:/secure-spool" \
        -D "Cipherjet (Encrypted)" -L "Secure encrypted spool" -m raw \
  || lpadmin -p "$QUEUE_NAME" -E -v "cipherjet:/secure-spool" \
        -D "Cipherjet (Encrypted)" -L "Secure encrypted spool"
cupsenable "$QUEUE_NAME" || true
cupsaccept "$QUEUE_NAME" || true

cat <<EOF

✔ Installed. "Cipherjet (Encrypted)" is now a printer you can select.

  Print to it from any app (⌘P → Cipherjet (Encrypted)) or via:
      lp -d $QUEUE_NAME somefile.pdf

  List and release the encrypted jobs (admin-only):
      sudo cipherjet-admin list
      sudo cipherjet-admin release <job-id> | lp -d IT_MONITORING_1
      sudo cipherjet-admin verify-audit

  To remove everything:  sudo ./install/uninstall-cups-printer.sh
EOF
